// src/plugins/vuetify.js
import { createVuetify } from "vuetify";
import "vuetify/styles";
import { aliases, mdi } from "vuetify/iconsets/mdi";
import "@mdi/font/css/materialdesignicons.css";

// Importación selectiva de componentes para tree-shaking
import {
  VApp,
  VMain,
  VContainer,
  VRow,
  VCol,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VBtn,
  VIcon,
  VChip,
  VTextField,
  VTextarea,
  VSelect,
  VForm,
  VAlert,
  VDialog,
  VProgressCircular,
  VMenu,
  VList,
  VListItem,
  VListItemTitle,
  VDivider,
  VNavigationDrawer,
  VAppBar,
  VToolbar,
  VToolbarTitle,
  VSpacer,
  VTabs,
  VTab,
  VTabsWindow,
  VTabsWindowItem,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelTitle,
  VExpansionPanelText,
  VSnackbar,
  VOverlay,
  VImg,
  VAvatar,
  VBadge,
  VTooltip,
  VCheckbox,
  VRadio,
  VRadioGroup,
  VSwitch,
  VSlider,
  VRangeSlider,
  VRating,
  VDataTable,
  VDataTableServer,
  VPagination,
  VBreadcrumbs,
  VBreadcrumbsItem,
  VCarousel,
  VCarouselItem,
  VTimeline,
  VTimelineItem,
  VBottomNavigation,
  VBottomNavigationBtn,
  VFab,
  VSpeedDial,
  VFileInput,
  VColorPicker,
  VDatePicker,
  VTimePicker,
  VAutocomplete,
  VCombobox,
  VBanner,
  VSheet,
  VSkeletonLoader,
  VProgressLinear,
  VSystemBar,
  VFooter,
  VTable,
  VVirtualScroll,
} from "vuetify/components";

import {
  VRipple,
  VIntersect,
  VResize,
  VScroll,
  VTouch,
  VMutate,
  VClickOutside,
} from "vuetify/directives";

const vuetify = createVuetify({
  components: {
    VApp,
    VMain,
    VContainer,
    VRow,
    VCol,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VBtn,
    VIcon,
    VChip,
    VTextField,
    VTextarea,
    VSelect,
    VForm,
    VAlert,
    VDialog,
    VProgressCircular,
    VMenu,
    VList,
    VListItem,
    VListItemTitle,
    VDivider,
    VNavigationDrawer,
    VAppBar,
    VToolbar,
    VToolbarTitle,
    VSpacer,
    VTabs,
    VTab,
    VTabsWindow,
    VTabsWindowItem,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelTitle,
    VExpansionPanelText,
    VSnackbar,
    VOverlay,
    VImg,
    VAvatar,
    VBadge,
    VTooltip,
    VCheckbox,
    VRadio,
    VRadioGroup,
    VSwitch,
    VSlider,
    VRangeSlider,
    VRating,
    VDataTable,
    VDataTableServer,
    VPagination,
    VBreadcrumbs,
    VBreadcrumbsItem,
    VCarousel,
    VCarouselItem,
    VTimeline,
    VTimelineItem,
    VBottomNavigation,
    VBottomNavigationBtn,
    VFab,
    VSpeedDial,
    VFileInput,
    VColorPicker,
    VDatePicker,
    VTimePicker,
    VAutocomplete,
    VCombobox,
    VBanner,
    VSheet,
    VSkeletonLoader,
    VProgressLinear,
    VSystemBar,
    VFooter,
    VTable,
    VVirtualScroll,
  },
  directives: {
    VRipple,
    VIntersect,
    VResize,
    VScroll,
    VTouch,
    VMutate,
    VClickOutside,
  },
  icons: {
    defaultSet: "mdi",
    aliases,
    sets: {
      mdi,
    },
  },
  theme: {
    defaultTheme: "dark",
    themes: {
      dark: {
        colors: {
          primary: "#0066ff",
          secondary: "#00cccc",
          accent: "#00a5a5",
          background: "#0a0a0a",
          surface: "#1a1a1a",
          "surface-variant": "rgba(255, 255, 255, 0.05)",
          "on-surface": "#ffffff",
          "on-surface-variant": "#cccccc",
          success: "#4caf50",
          warning: "#ff9800",
          error: "#f44336",
          info: "#2196f3",
        },
      },
    },
  },
  defaults: {
    VBtn: {
      style: "text-transform: none;",
      ripple: true,
    },
    VCard: {
      elevation: 2,
    },
    VTextField: {
      variant: "outlined",
      density: "comfortable",
    },
    VTextarea: {
      variant: "outlined",
      density: "comfortable",
    },
    VSelect: {
      variant: "outlined",
      density: "comfortable",
    },
  },
});

export default vuetify;
